#!/bin/bash

##################################################
# Script that can be used to set up specific     #
# environment variables for Artemis and related  #
# applications.                                  #
# Uncomment as required and run before startup.  #
#                                                #
##################################################

#
# Set the location of a specific JRE to use
# for all Artemis related applications.
#
#export ARTEMIS_JAVA_JRE=

#
# Set specific java JVM flags for memory management etc.
#
#export ARTEMIS_JVM_FLAGS=

#
# Chado database connectivity.
#
#export PGHOST=
#export PGPORT=
#export PGDATABASE=
#export PGUSER=

#
# Specify locally installed Blast databases,
# e.g. /data/blastdb/Supported/UNIPROT/current:/data/blastdb/Supported/EMBL/current/con etc
#
#export BLASTDB=


                         