#!/bin/bash

##################################################
# Script that can be used to set up specific     #
# environment variables for Artemis and related  #
# applications.                                  #
# Uncomment as required and either run from your #
# shell .profile or copy and paste the variables #
# directly into your shell profile.              #
#                                                #
##################################################

#
# Set the location of a specific JRE to use
# for all Artemis related applications.
#
#export ARTEMIS_JAVA_JRE=

#
# Set specific java JVM flags for memory management etc.
#
#export ARTEMIS_JVM_FLAGS=

#
# Chado database connectivity.
#
#export PGHOST=
#export PGPORT=
#export PGDATABASE=
#export PGUSER=

########### Variables for locally installed Blast databases ##############

#
# Use the following path setting to specify
# where blast+ executables can be found.
# Change as required.
#
#export PATH=/usr/local/ncbi/blast/bin/:$PATH

#
# Specify locally installed Blast databases.
# [See NCBI Blast+ documentation]
# e.g. /data/blastdb/Supported/UNIPROT/current:/data/blastdb/Supported/EMBL/current/con etc
#
#export BLASTDB=

                