/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Jan 12 12:34:14 GMT 2018
 */

package uk.ac.sanger.artemis.components.genebuilder;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class OpenSectionButton_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "uk.ac.sanger.artemis.components.genebuilder.OpenSectionButton"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.country", "GB"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "Europe/London"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(OpenSectionButton_ESTest_scaffolding.class.getClassLoader() ,
      "htsjdk.variant.vcf.VCFHeaderLine",
      "uk.ac.sanger.artemis.components.genebuilder.gff.AddButton",
      "uk.ac.sanger.artemis.components.SwingWorker",
      "uk.ac.sanger.artemis.ChangeListener",
      "uk.ac.sanger.artemis.components.genebuilder.OpenSectionButton",
      "uk.ac.sanger.artemis.editor.MultiLineToolTipUI",
      "uk.ac.sanger.artemis.components.genebuilder.ortholog.MatchPanel",
      "uk.ac.sanger.artemis.components.genebuilder.gff.RemoveButton",
      "uk.ac.sanger.artemis.components.genebuilder.gff.PropertiesPanel",
      "htsjdk.tribble.TribbleException",
      "uk.ac.sanger.artemis.components.genebuilder.ortholog.MatchPanel$3",
      "org.apache.log4j.Hierarchy",
      "uk.ac.sanger.artemis.components.genebuilder.JExtendedComboBox",
      "org.apache.log4j.Logger",
      "uk.ac.sanger.artemis.components.genebuilder.GeneEditorPanel",
      "org.emboss.jemboss.gui.Browser$3",
      "org.emboss.jemboss.gui.Browser$4",
      "org.emboss.jemboss.gui.MemoryComboBox",
      "uk.ac.sanger.artemis.components.genebuilder.JExtendedComboBox$ComboBoxRenderer",
      "uk.ac.sanger.artemis.components.QualifierTextArea$2",
      "org.apache.log4j.Level",
      "uk.ac.sanger.artemis.EntryGroup",
      "uk.ac.sanger.artemis.components.genebuilder.cv.CVPanel",
      "uk.ac.sanger.artemis.io.Feature",
      "uk.ac.sanger.artemis.components.genebuilder.ReferencesPanel",
      "org.emboss.jemboss.gui.Browser$6",
      "uk.ac.sanger.artemis.components.genebuilder.AutoCompleteComboDocument",
      "htsjdk.tribble.TribbleException$InternalCodecException",
      "org.emboss.jemboss.gui.Browser",
      "org.apache.log4j.Category",
      "uk.ac.sanger.artemis.components.QualifierTextArea",
      "org.apache.log4j.spi.RootLogger",
      "org.emboss.jemboss.gui.Browser$JIconButton",
      "uk.ac.sanger.artemis.EntryChangeListener",
      "org.apache.batik.ext.awt.ColorSpaceHintKey",
      "org.apache.log4j.spi.AppenderAttachable",
      "uk.ac.sanger.artemis.io.ReadFormatException",
      "org.apache.log4j.spi.RepositorySelector",
      "org.apache.log4j.spi.RendererSupport",
      "uk.ac.sanger.artemis.FeatureChangeListener",
      "uk.ac.sanger.artemis.io.QualifierParseException",
      "org.apache.log4j.Priority",
      "uk.ac.sanger.artemis.io.Entry",
      "org.apache.log4j.spi.LoggerRepository",
      "org.apache.log4j.LogManager",
      "uk.ac.sanger.artemis.components.genebuilder.OpenSectionButton$1",
      "org.emboss.jemboss.JembossParams"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(OpenSectionButton_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "uk.ac.sanger.artemis.components.genebuilder.OpenSectionButton",
      "uk.ac.sanger.artemis.components.genebuilder.GeneEditorPanel",
      "org.emboss.jemboss.gui.Browser",
      "org.emboss.jemboss.JembossParams",
      "uk.ac.sanger.artemis.components.genebuilder.JExtendedComboBox",
      "uk.ac.sanger.artemis.components.genebuilder.JExtendedComboBox$ComboBoxRenderer",
      "org.apache.batik.ext.awt.ColorSpaceHintKey",
      "uk.ac.sanger.artemis.components.genebuilder.AutoCompleteComboDocument",
      "htsjdk.variant.vcf.VCFHeaderLine"
    );
  }
}
