/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 10 13:23:47 GMT 2018
 */

package uk.ac.sanger.artemis;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sanger.artemis.OptionChangeEvent;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ChangeEvent_ESTest extends ChangeEvent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OptionChangeEvent optionChangeEvent0 = new OptionChangeEvent("2W=JJO8<cQe@H}", "");
      assertEquals("", optionChangeEvent0.getOptionName());
  }
}
