/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 12 10:38:40 GMT 2018
 */

package uk.ac.sanger.artemis;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sanger.artemis.ChangeEvent;
import uk.ac.sanger.artemis.ChangeEventVector;
import uk.ac.sanger.artemis.components.DisplayAdjustmentEvent;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ChangeEventVector_ESTest extends ChangeEventVector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChangeEventVector changeEventVector0 = new ChangeEventVector();
      changeEventVector0.add((ChangeEvent) null);
      int int0 = changeEventVector0.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ChangeEventVector changeEventVector0 = new ChangeEventVector();
      DisplayAdjustmentEvent displayAdjustmentEvent0 = new DisplayAdjustmentEvent(changeEventVector0, 0, 0, 2624, 0, 0, true, (-9));
      changeEventVector0.add(displayAdjustmentEvent0);
      DisplayAdjustmentEvent displayAdjustmentEvent1 = (DisplayAdjustmentEvent)changeEventVector0.elementAt(0);
      assertEquals(4, DisplayAdjustmentEvent.CONTIG_REV_COMP_EVENT);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ChangeEventVector changeEventVector0 = new ChangeEventVector();
      changeEventVector0.add((ChangeEvent) null);
      ChangeEvent changeEvent0 = changeEventVector0.elementAt(0);
      assertNull(changeEvent0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ChangeEventVector changeEventVector0 = new ChangeEventVector();
      // Undeclared exception!
      try { 
        changeEventVector0.elementAt(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0 >= 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ChangeEventVector changeEventVector0 = new ChangeEventVector();
      int int0 = changeEventVector0.size();
      assertEquals(0, int0);
  }
}
