/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 12 15:46:17 GMT 2018
 */

package uk.ac.sanger.artemis;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.CharArrayReader;
import java.io.LineNumberReader;
import java.io.Reader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sanger.artemis.components.LogViewer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Logger_ESTest extends Logger_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LogViewer logViewer0 = new LogViewer();
      // Undeclared exception!
      try { 
        logViewer0.log("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class uk.ac.sanger.artemis.components.LogViewer$1
         //
         verifyException("uk.ac.sanger.artemis.components.LogViewer", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LogViewer logViewer0 = new LogViewer();
      char[] charArray0 = new char[6];
      CharArrayReader charArrayReader0 = new CharArrayReader(charArray0, 0, 0);
      LineNumberReader lineNumberReader0 = new LineNumberReader(charArrayReader0);
      // Undeclared exception!
      try { 
        logViewer0.log((Reader) lineNumberReader0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class uk.ac.sanger.artemis.components.LogViewer$1
         //
         verifyException("uk.ac.sanger.artemis.components.LogViewer", e);
      }
  }
}
