/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 08 20:25:39 GMT 2018
 */

package uk.ac.sanger.artemis.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sanger.artemis.util.ReadOnlyException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class ReadOnlyException_ESTest extends ReadOnlyException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ReadOnlyException readOnlyException0 = new ReadOnlyException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ReadOnlyException readOnlyException0 = new ReadOnlyException(".c?-nisaD0(");
  }
}
