/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 29 01:51:24 GMT 2017
 */

package uk.ac.sanger.artemis.components;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Dimension;
import java.awt.Graphics;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sanger.artemis.Entry;
import uk.ac.sanger.artemis.Feature;
import uk.ac.sanger.artemis.components.DisplayAdjustmentEvent;
import uk.ac.sanger.artemis.components.FeaturePlot;
import uk.ac.sanger.artemis.io.EmblStreamFeature;
import uk.ac.sanger.artemis.io.EmblStreamSequence;
import uk.ac.sanger.artemis.io.GenbankStreamFeature;
import uk.ac.sanger.artemis.plot.CoilFeatureAlgorithm;
import uk.ac.sanger.artemis.plot.FeatureAlgorithm;
import uk.ac.sanger.artemis.plot.HydrophilicityAlgorithm;
import uk.ac.sanger.artemis.plot.HydrophobicityAlgorithm;
import uk.ac.sanger.artemis.plot.LineAttributes;
import uk.ac.sanger.artemis.sequence.Bases;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FeaturePlot_ESTest extends FeaturePlot_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GenbankStreamFeature genbankStreamFeature0 = new GenbankStreamFeature();
      Feature feature0 = new Feature(genbankStreamFeature0);
      CoilFeatureAlgorithm coilFeatureAlgorithm0 = new CoilFeatureAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(coilFeatureAlgorithm0);
      int int0 = featurePlot0.getPointPosition((-3509));
      assertEquals((-3508), int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EmblStreamSequence emblStreamSequence0 = new EmblStreamSequence("<em,mHwT-WJLAT=");
      Bases bases0 = new Bases(emblStreamSequence0);
      Entry entry0 = Entry.newEntry(bases0);
      Feature feature0 = entry0.createFeature();
      HydrophilicityAlgorithm hydrophilicityAlgorithm0 = new HydrophilicityAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(hydrophilicityAlgorithm0);
      featurePlot0.setBounds(0, 0, 49152, 522);
      Dimension dimension0 = featurePlot0.getMinimumSize();
      assertEquals(49152, dimension0.width);
      assertEquals(160, dimension0.height);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EmblStreamFeature emblStreamFeature0 = new EmblStreamFeature();
      Feature feature0 = new Feature(emblStreamFeature0);
      HydrophobicityAlgorithm hydrophobicityAlgorithm0 = new HydrophobicityAlgorithm(feature0);
      hydrophobicityAlgorithm0.setScalingFlag(true);
      FeaturePlot featurePlot0 = new FeaturePlot(hydrophobicityAlgorithm0);
      FeatureAlgorithm featureAlgorithm0 = featurePlot0.getFeatureAlgorithm();
      assertEquals(3.4028235E38F, featureAlgorithm0.getUserMax(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EmblStreamFeature emblStreamFeature0 = new EmblStreamFeature();
      Feature feature0 = new Feature(emblStreamFeature0);
      HydrophobicityAlgorithm hydrophobicityAlgorithm0 = new HydrophobicityAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(hydrophobicityAlgorithm0);
      hydrophobicityAlgorithm0.setUserMin(0.0F);
      FeatureAlgorithm featureAlgorithm0 = featurePlot0.getFeatureAlgorithm();
      assertSame(hydrophobicityAlgorithm0, featureAlgorithm0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EmblStreamFeature emblStreamFeature0 = new EmblStreamFeature();
      Feature feature0 = new Feature(emblStreamFeature0);
      HydrophobicityAlgorithm hydrophobicityAlgorithm0 = new HydrophobicityAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(hydrophobicityAlgorithm0);
      // Undeclared exception!
      try { 
        featurePlot0.displayAdjustmentValueChanged((DisplayAdjustmentEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.components.FeaturePlot", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FeaturePlot featurePlot0 = null;
      try {
        featurePlot0 = new FeaturePlot((FeatureAlgorithm) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.components.Plot", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GenbankStreamFeature genbankStreamFeature0 = new GenbankStreamFeature();
      Feature feature0 = new Feature(genbankStreamFeature0);
      CoilFeatureAlgorithm coilFeatureAlgorithm0 = new CoilFeatureAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(coilFeatureAlgorithm0);
      LineAttributes[] lineAttributesArray0 = new LineAttributes[8];
      // Undeclared exception!
      try { 
        featurePlot0.drawMultiValueGraph((Graphics) null, lineAttributesArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.components.Plot", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EmblStreamFeature emblStreamFeature0 = new EmblStreamFeature();
      Feature feature0 = new Feature(emblStreamFeature0);
      HydrophobicityAlgorithm hydrophobicityAlgorithm0 = new HydrophobicityAlgorithm(feature0);
      hydrophobicityAlgorithm0.setScalingFlag(true);
      FeaturePlot featurePlot0 = new FeaturePlot(hydrophobicityAlgorithm0);
      featurePlot0.recalculateValues();
      assertFalse(featurePlot0.isFocusCycleRoot());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EmblStreamFeature emblStreamFeature0 = new EmblStreamFeature();
      Feature feature0 = new Feature(emblStreamFeature0);
      HydrophobicityAlgorithm hydrophobicityAlgorithm0 = new HydrophobicityAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(hydrophobicityAlgorithm0);
      featurePlot0.calculateFeatures(false);
      assertTrue(featurePlot0.getFocusTraversalKeysEnabled());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EmblStreamSequence emblStreamSequence0 = new EmblStreamSequence("<em,mHwT-WJLAT=");
      Bases bases0 = new Bases(emblStreamSequence0);
      Entry entry0 = Entry.newEntry(bases0);
      Feature feature0 = entry0.createFeature();
      HydrophilicityAlgorithm hydrophilicityAlgorithm0 = new HydrophilicityAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(hydrophilicityAlgorithm0);
      int int0 = featurePlot0.getPointPosition(5);
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EmblStreamFeature emblStreamFeature0 = new EmblStreamFeature();
      Feature feature0 = new Feature(emblStreamFeature0);
      CoilFeatureAlgorithm coilFeatureAlgorithm0 = new CoilFeatureAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(coilFeatureAlgorithm0);
      DisplayAdjustmentEvent displayAdjustmentEvent0 = new DisplayAdjustmentEvent(coilFeatureAlgorithm0, 3482, 0, 0, 2949.0F, 300, false, 1);
      featurePlot0.displayAdjustmentValueChanged(displayAdjustmentEvent0);
      featurePlot0.recalculateValues();
      assertFalse(featurePlot0.isFocusTraversalPolicyProvider());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EmblStreamFeature emblStreamFeature0 = new EmblStreamFeature();
      Feature feature0 = new Feature(emblStreamFeature0);
      HydrophobicityAlgorithm hydrophobicityAlgorithm0 = new HydrophobicityAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(hydrophobicityAlgorithm0);
      featurePlot0.showAveragesForRange();
      assertTrue(featurePlot0.getFocusTraversalKeysEnabled());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EmblStreamSequence emblStreamSequence0 = new EmblStreamSequence("<em,mHwT-WJLAT=");
      Bases bases0 = new Bases(emblStreamSequence0);
      Entry entry0 = Entry.newEntry(bases0);
      Feature feature0 = entry0.createFeature();
      HydrophilicityAlgorithm hydrophilicityAlgorithm0 = new HydrophilicityAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(hydrophilicityAlgorithm0);
      featurePlot0.stopListening();
      assertFalse(featurePlot0.isFocusCycleRoot());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EmblStreamSequence emblStreamSequence0 = new EmblStreamSequence("<em,mHwT-WJLAT=");
      Bases bases0 = new Bases(emblStreamSequence0);
      Entry entry0 = Entry.newEntry(bases0);
      Feature feature0 = entry0.createFeature();
      HydrophilicityAlgorithm hydrophilicityAlgorithm0 = new HydrophilicityAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(hydrophilicityAlgorithm0);
      Dimension dimension0 = featurePlot0.getMinimumSize();
      assertEquals(160, dimension0.height);
      assertEquals(0, dimension0.width);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      EmblStreamSequence emblStreamSequence0 = new EmblStreamSequence("<em,mHwT-WJLAT=");
      Bases bases0 = new Bases(emblStreamSequence0);
      Entry entry0 = Entry.newEntry(bases0);
      Feature feature0 = entry0.createFeature();
      HydrophilicityAlgorithm hydrophilicityAlgorithm0 = new HydrophilicityAlgorithm(feature0);
      FeaturePlot featurePlot0 = new FeaturePlot(hydrophilicityAlgorithm0);
      Dimension dimension0 = featurePlot0.getPreferredSize();
      assertEquals(160, dimension0.height);
      assertEquals(0, dimension0.width);
  }
}
