/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 29 03:16:45 GMT 2017
 */

package uk.ac.sanger.artemis.components;

import org.junit.Test;
import static org.junit.Assert.*;
import java.awt.datatransfer.Clipboard;
import javax.swing.JFrame;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sanger.artemis.EntryGroup;
import uk.ac.sanger.artemis.Selection;
import uk.ac.sanger.artemis.SimpleEntryGroup;
import uk.ac.sanger.artemis.components.WriteMenu;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WriteMenu_ESTest extends WriteMenu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Clipboard clipboard0 = new Clipboard("]i>8sdS~wiNh9");
      Selection selection0 = new Selection(clipboard0);
      WriteMenu writeMenu0 = new WriteMenu((JFrame) null, selection0, (EntryGroup) null);
      assertFalse(writeMenu0.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Clipboard clipboard0 = new Clipboard("");
      Selection selection0 = new Selection(clipboard0);
      SimpleEntryGroup simpleEntryGroup0 = new SimpleEntryGroup();
      WriteMenu writeMenu0 = new WriteMenu((JFrame) null, selection0, simpleEntryGroup0, "");
      assertFalse(writeMenu0.isFocusTraversalPolicySet());
  }
}
