/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 12 11:14:16 GMT 2018
 */

package uk.ac.sanger.artemis.components.alignment;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sanger.artemis.components.alignment.BamOSXAdapter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BamOSXAdapter_ESTest extends BamOSXAdapter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Object object0 = new Object();
      BamOSXAdapter.setAboutHandler(object0, (Method) null);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BamOSXAdapter.macOSXApplication = (Object) null;
      BamOSXAdapter.macOSXApplication = (Object) "";
      BamOSXAdapter.setPreferencesHandler("", (Method) null);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BamOSXAdapter bamOSXAdapter0 = new BamOSXAdapter((String) null, (Object) null, (Method) null);
      Object[] objectArray0 = new Object[0];
      boolean boolean0 = bamOSXAdapter0.isCorrectMethod((Method) null, objectArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BamOSXAdapter bamOSXAdapter0 = new BamOSXAdapter("8 mc(!lsC<9]|y", "8 mc(!lsC<9]|y", (Method) null);
      // Undeclared exception!
      try { 
        BamOSXAdapter.setHandler(bamOSXAdapter0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class com.apple.eawt.Application
         //
         verifyException("java.lang.Class", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BamOSXAdapter bamOSXAdapter0 = new BamOSXAdapter("/Dg,f~OWLRG>N T j", "/Dg,f~OWLRG>N T j", (Method) null);
      // Undeclared exception!
      try { 
        bamOSXAdapter0.callTarget((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.components.alignment.BamOSXAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BamOSXAdapter bamOSXAdapter0 = new BamOSXAdapter("/Dg,f~OWLRG>N T j", "/Dg,f~OWLRG>N T j", (Method) null);
      bamOSXAdapter0.setApplicationEventHandled("/Dg,f~OWLRG>N T j", false);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BamOSXAdapter bamOSXAdapter0 = new BamOSXAdapter((String) null, (Object) null, (Method) null);
      bamOSXAdapter0.setApplicationEventHandled((Object) null, false);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BamOSXAdapter bamOSXAdapter0 = new BamOSXAdapter("8 mc(!lsC<9]|y", "8 mc(!lsC<9]|y", (Method) null);
      Object[] objectArray0 = new Object[3];
      Object object0 = bamOSXAdapter0.invoke((Object) null, (Method) null, objectArray0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BamOSXAdapter.setPreferencesHandler((Object) null, (Method) null);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BamOSXAdapter bamOSXAdapter0 = new BamOSXAdapter("/Dg,f~OWLRG>N T j", "/Dg,f~OWLRG>N T j", (Method) null);
      BamOSXAdapter.macOSXApplication = (Object) bamOSXAdapter0;
      BamOSXAdapter.setAboutHandler(BamOSXAdapter.macOSXApplication, (Method) null);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BamOSXAdapter.setAboutHandler((Object) null, (Method) null);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Object object0 = new Object();
      BamOSXAdapter bamOSXAdapter0 = new BamOSXAdapter("", object0, (Method) null);
      // Undeclared exception!
      try { 
        BamOSXAdapter.setQuitHandler(bamOSXAdapter0, (Method) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class com.apple.eawt.Application
         //
         verifyException("java.lang.Class", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BamOSXAdapter bamOSXAdapter0 = new BamOSXAdapter(" isn't annotated.", " isn't annotated.", (Method) null);
      // Undeclared exception!
      try { 
        BamOSXAdapter.setFileHandler(bamOSXAdapter0.targetObject, (Method) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class com.apple.eawt.Application
         //
         verifyException("java.lang.Class", e);
      }
  }
}
