/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 29 01:13:06 GMT 2017
 */

package uk.ac.sanger.artemis.components.alignment;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import uk.ac.sanger.artemis.components.alignment.FileSelectionDialog;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileSelectionDialog_ESTest extends FileSelectionDialog_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      boolean boolean0 = FileSelectionDialog.isListOfFiles("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        FileSelectionDialog.isListOfFiles((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      // Undeclared exception!
      try { 
        FileSelectionDialog.getListOfFiles((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[1];
      FileSelectionDialog fileSelectionDialog0 = null;
      try {
        fileSelectionDialog0 = new FileSelectionDialog(stringArray0);
        fail("Expecting exception: HeadlessException");
      
      } catch(HeadlessException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.awt.GraphicsEnvironment", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FileSelectionDialog fileSelectionDialog0 = null;
      try {
        fileSelectionDialog0 = new FileSelectionDialog((Frame) null, false, "proxy.override", "proxy.override");
        fail("Expecting exception: HeadlessException");
      
      } catch(HeadlessException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.awt.GraphicsEnvironment", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile(CURRENT_DIR + "/B_7");
      byte[] byteArray0 = new byte[8];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      List<String> list0 = FileSelectionDialog.getListOfFiles("B_7");
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile(CURRENT_DIR + "/B_7");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "http://www.uk.embnet.org/Software/EMBOSS/Apps/");
      List<String> list0 = FileSelectionDialog.getListOfFiles("B_7");
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      List<String> list0 = FileSelectionDialog.getListOfFiles("http://www.uk.embnet.org/Software/EMBOSS/Apps/");
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      List<String> list0 = FileSelectionDialog.getListOfFiles("B_7");
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile(CURRENT_DIR + "/B_7");
      byte[] byteArray0 = new byte[8];
      byteArray0[3] = (byte) (-89);
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      boolean boolean0 = FileSelectionDialog.isListOfFiles("B_7");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile(CURRENT_DIR + "/user.home");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "user.home");
      boolean boolean0 = FileSelectionDialog.isListOfFiles("user.home");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile(CURRENT_DIR + "/B_7");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "ftpftp");
      boolean boolean0 = FileSelectionDialog.isListOfFiles("B_7");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile(CURRENT_DIR + "/B_7");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "http://www.uk.embnet.org/Software/EMBOSS/Apps/");
      boolean boolean0 = FileSelectionDialog.isListOfFiles("B_7");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      boolean boolean0 = FileSelectionDialog.isListOfFiles("ftpuk.ac.sanger.artemis.components.alignment.FileSelectionDialog");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      boolean boolean0 = FileSelectionDialog.isListOfFiles("B_7");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      boolean boolean0 = FileSelectionDialog.isListOfFiles("httphttp://www.uk.embnet.org/Software/EMBOSS/Apps/");
      assertFalse(boolean0);
  }
}
