/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 10 12:32:38 GMT 2018
 */

package uk.ac.sanger.artemis.cramtools.ref;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReferenceRegion_ESTest extends ReferenceRegion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      ReferenceRegion referenceRegion0 = ReferenceRegion.copyRegion(byteArray0, 90, ", alignmentStart=", 90, (byte) (-52));
      // Undeclared exception!
      try { 
        referenceRegion0.md5(0, (byte) (-52));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      ReferenceRegion referenceRegion0 = new ReferenceRegion(byteArray0, 87, "", 87);
      referenceRegion0.md5(87, 87);
      assertEquals(87, referenceRegion0.index);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      byte[] byteArray0 = new byte[8];
      ReferenceRegion referenceRegion0 = ReferenceRegion.copyRegion(byteArray0, (byte)3, "", 1L, 511L);
      assertEquals(1L, referenceRegion0.alignmentStart);
      
      byte[] byteArray1 = referenceRegion0.copySafe(4L, (int) (byte)3);
      assertEquals(3, referenceRegion0.index);
      assertEquals(3, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      ReferenceRegion referenceRegion0 = new ReferenceRegion(byteArray0, 5123, "S", 5123);
      byte[] byteArray1 = referenceRegion0.copySafe((long) 5123, 5123);
      assertEquals(5123, referenceRegion0.index);
      assertEquals(0, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap(byteArray0, (byte)31, "]");
      assertEquals(1L, referenceRegion0.alignmentStart);
      
      referenceRegion0.alignmentStart = (long) (byte)0;
      byte[] byteArray1 = referenceRegion0.copy((byte)0, (byte)0);
      assertEquals(0, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ReferenceRegion referenceRegion0 = new ReferenceRegion(byteArray0, 425, ") without a corresponding deletion in cigar (", 425);
      referenceRegion0.base(425);
      assertEquals(425, referenceRegion0.index);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)114;
      ReferenceRegion referenceRegion0 = new ReferenceRegion(byteArray0, (byte)45, "`O 9:KL)OH&<*'/", (byte)45);
      byte byte0 = referenceRegion0.base((byte)45);
      assertEquals(45, referenceRegion0.index);
      assertEquals((byte)114, byte0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte) (-102);
      ReferenceRegion referenceRegion0 = new ReferenceRegion(byteArray0, (byte)45, "`OGXKLOH&<*/", (byte)45);
      byte byte0 = referenceRegion0.base((byte)45);
      assertEquals(45, referenceRegion0.index);
      assertEquals((byte) (-102), byte0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap(byteArray0, 1, "]");
      int int0 = referenceRegion0.arrayPosition((byte)2);
      assertEquals(1, int0);
      assertEquals(1, referenceRegion0.index);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap((byte[]) null, 679, "");
      // Undeclared exception!
      try { 
        referenceRegion0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ReferenceRegion referenceRegion0 = new ReferenceRegion((byte[]) null, 3457, "", 854L);
      // Undeclared exception!
      try { 
        referenceRegion0.md5(366, (-2412));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap(byteArray0, 4, "");
      referenceRegion0.alignmentStart = 1028L;
      // Undeclared exception!
      try { 
        referenceRegion0.md5(4, 806);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        ReferenceRegion.copySafe((byte[]) null, 0L, 0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      // Undeclared exception!
      try { 
        ReferenceRegion.copySafe(byteArray0, 0L, (-84), (-1210));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -84 > -1294
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap((byte[]) null, 1, "");
      // Undeclared exception!
      try { 
        referenceRegion0.copySafe(1L, (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      ReferenceRegion referenceRegion0 = new ReferenceRegion(byteArray0, (-483), ", array length=", 1935L);
      // Undeclared exception!
      try { 
        referenceRegion0.copySafe((long) (byte)38, (-406));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -1897 > -2303
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      // Undeclared exception!
      try { 
        ReferenceRegion.copyRegion((byte[]) null, 2647, "", 2647, 2647);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      // Undeclared exception!
      try { 
        ReferenceRegion.copyRegion(byteArray0, 0, "", (byte)7, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 6 > 0
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      // Undeclared exception!
      try { 
        ReferenceRegion.copyRegion(byteArray0, (byte)0, "ta%@y6zby(4Q\"AJEO", (-1643L), 1L);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap((byte[]) null, 2, "c");
      // Undeclared exception!
      try { 
        referenceRegion0.copy(2, 2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap(byteArray0, (byte)94, "htsjdk.samtools.util.SequenceUtil");
      // Undeclared exception!
      try { 
        referenceRegion0.copy(2L, (byte) (-96));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The alignment position is out of the region: 1, -94, 0, -95
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap((byte[]) null, (-2946), "");
      // Undeclared exception!
      try { 
        referenceRegion0.base((-2946));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap((byte[]) null, 2, ".aAbBcCdDgGhHkKmMnNrRsStTvVwWyY");
      // Undeclared exception!
      try { 
        referenceRegion0.arrayPosition(0L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ReferenceRegion referenceRegion0 = null;
      try {
        referenceRegion0 = new ReferenceRegion((byte[]) null, (-1), "+<0X9", (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap(byteArray0, (byte)0, (String) null);
      // Undeclared exception!
      try { 
        ReferenceRegion.copySafe(referenceRegion0.array, 795L, (int) (byte)0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      byte[] byteArray1 = ReferenceRegion.copySafe(byteArray0, 0L, (int) (byte)112, (int) (byte)112);
      assertEquals(0, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ReferenceRegion referenceRegion0 = new ReferenceRegion(byteArray0, 612, "", 4051L);
      assertEquals(4051L, referenceRegion0.alignmentStart);
      
      int int0 = referenceRegion0.arrayPosition(4051L);
      assertEquals(612, referenceRegion0.index);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ReferenceRegion referenceRegion0 = new ReferenceRegion(byteArray0, 612, "", 4051L);
      // Undeclared exception!
      try { 
        referenceRegion0.arrayPosition((byte)31);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The alignment position is out of the region: 4051, 31, 0, -4020
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap(byteArray0, (-1959), "");
      String string0 = referenceRegion0.toString();
      assertEquals("ReferenceRegion [index=-1959, name=, alignmentStart=1, array length=9]", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap(byteArray0, (byte)0, "");
      String string0 = referenceRegion0.md5(16, 0);
      assertEquals(1L, referenceRegion0.alignmentStart);
      assertEquals(0, referenceRegion0.index);
      assertEquals("d41d8cd98f00b204e9800998ecf8427e", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      byte[] byteArray1 = ReferenceRegion.copySafe(byteArray0, (long) (byte)0, (int) (byte)0, (int) (byte)99);
      assertEquals(7, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap(byteArray0, (byte)0, "");
      // Undeclared exception!
      try { 
        referenceRegion0.arrayPosition(4025L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The alignment position is out of the region: 1, 4025, 0, 4024
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      ReferenceRegion referenceRegion0 = null;
      try {
        referenceRegion0 = new ReferenceRegion(byteArray0, (-683), "h|YSGmJ;F=HTz*/", (-683));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid reference region1: h|YSGmJ;F=HTz*_/, -683, 3.
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap(byteArray0, 352, "<$Q@uW-0Cpq");
      // Undeclared exception!
      try { 
        referenceRegion0.copySafe((-1L), 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap(byteArray0, (byte)99, "");
      byte[] byteArray1 = referenceRegion0.copy((byte)3, (byte)3);
      assertEquals(1L, referenceRegion0.alignmentStart);
      assertEquals(99, referenceRegion0.index);
      assertEquals(3, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      ReferenceRegion referenceRegion0 = ReferenceRegion.wrap(byteArray0, (byte)99, "");
      // Undeclared exception!
      try { 
        referenceRegion0.base((byte)0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The alignment position is out of the region: 1, 0, 0, -1
         //
         verifyException("uk.ac.sanger.artemis.cramtools.ref.ReferenceRegion", e);
      }
  }
}
