/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Sep 20 11:54:30 GMT 2018
 */

package uk.ac.sanger.artemis.components.variant;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TabixReader_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "uk.ac.sanger.artemis.components.variant.TabixReader"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/r3/l648tx8s7hn8ppds6z2bk5cc000h2n/T/"); 
    java.lang.System.setProperty("user.country", "GB"); 
    java.lang.System.setProperty("user.dir", "/Users/kp11/workspace/applications/Artemis-build-ci/Artemis"); 
    java.lang.System.setProperty("user.home", "/Users/kp11"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "kp11"); 
    java.lang.System.setProperty("user.timezone", ""); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TabixReader_ESTest_scaffolding.class.getClassLoader() ,
      "htsjdk.samtools.seekablestream.SeekableBufferedStream",
      "htsjdk.samtools.seekablestream.SeekableBufferedStream$ExtBufferedInputStream",
      "htsjdk.samtools.seekablestream.SeekableHTTPStream",
      "uk.ac.sanger.artemis.ChangeListener",
      "htsjdk.samtools.SAMFormatException",
      "uk.ac.sanger.artemis.components.variant.TabixReader$TIndex",
      "uk.ac.sanger.artemis.components.variant.TabixReader$TPair64",
      "htsjdk.samtools.FileTruncatedException",
      "htsjdk.samtools.seekablestream.ByteArraySeekableStream",
      "htsjdk.samtools.seekablestream.SeekableFileStream",
      "uk.ac.sanger.artemis.components.variant.TabixReader",
      "htsjdk.samtools.util.BlockCompressedInputStream$DecompressedBlock",
      "htsjdk.samtools.util.RuntimeIOException",
      "uk.ac.sanger.artemis.FeatureVector",
      "uk.ac.sanger.artemis.components.variant.VCFview",
      "htsjdk.samtools.SAMException",
      "htsjdk.samtools.util.BlockCompressedInputStream",
      "uk.ac.sanger.artemis.components.variant.TabixReader$TIntv",
      "uk.ac.sanger.artemis.components.DisplayAdjustmentListener",
      "uk.ac.sanger.artemis.components.variant.BCFReader",
      "uk.ac.sanger.artemis.components.variant.VCFRecord",
      "htsjdk.samtools.util.zip.InflaterFactory",
      "htsjdk.samtools.util.LocationAware",
      "uk.ac.sanger.artemis.components.variant.TabixReader$Iterator",
      "htsjdk.samtools.seekablestream.SeekableStream",
      "htsjdk.samtools.util.HttpUtils",
      "uk.ac.sanger.artemis.components.variant.AbstractVCFReader",
      "uk.ac.sanger.artemis.SelectionChangeListener",
      "htsjdk.samtools.util.BlockGunzipper"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TabixReader_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "uk.ac.sanger.artemis.components.variant.AbstractVCFReader",
      "uk.ac.sanger.artemis.components.variant.TabixReader",
      "uk.ac.sanger.artemis.components.variant.TabixReader$TIndex",
      "uk.ac.sanger.artemis.components.variant.TabixReader$TPair64",
      "uk.ac.sanger.artemis.components.variant.TabixReader$TIntv",
      "uk.ac.sanger.artemis.components.variant.TabixReader$Iterator",
      "htsjdk.samtools.util.BlockCompressedInputStream",
      "htsjdk.samtools.util.zip.InflaterFactory",
      "htsjdk.samtools.util.BlockGunzipper",
      "htsjdk.samtools.seekablestream.SeekableStream",
      "htsjdk.samtools.seekablestream.SeekableBufferedStream",
      "htsjdk.samtools.seekablestream.SeekableHTTPStream",
      "htsjdk.samtools.util.HttpUtils",
      "htsjdk.samtools.seekablestream.SeekableBufferedStream$ExtBufferedInputStream",
      "htsjdk.samtools.seekablestream.SeekableFileStream",
      "htsjdk.samtools.util.BlockCompressedInputStream$DecompressedBlock",
      "htsjdk.samtools.SAMException",
      "htsjdk.samtools.FileTruncatedException",
      "htsjdk.samtools.seekablestream.ByteArraySeekableStream",
      "htsjdk.samtools.seekablestream.SeekableMemoryStream",
      "uk.ac.sanger.artemis.util.Document",
      "uk.ac.sanger.artemis.util.FileDocument",
      "uk.ac.sanger.artemis.util.ZipFileDocument",
      "uk.ac.sanger.artemis.util.InputStreamProgressListenerVector",
      "uk.ac.sanger.artemis.util.ProgressInputStream",
      "htsjdk.samtools.util.Log$LogLevel",
      "htsjdk.samtools.util.Log",
      "htsjdk.samtools.seekablestream.SeekablePathStream",
      "htsjdk.samtools.seekablestream.SeekableFTPStream",
      "htsjdk.samtools.seekablestream.SeekableFTPStreamHelper",
      "htsjdk.samtools.util.ftp.FTPUtils",
      "htsjdk.samtools.util.ftp.FTPClient",
      "uk.ac.sanger.artemis.j2ssh.SshFileManager",
      "uk.ac.sanger.artemis.j2ssh.SshLogin",
      "com.sshtools.j2ssh.io.ByteArrayReader",
      "com.sshtools.j2ssh.io.UnsignedInteger32",
      "uk.ac.sanger.artemis.util.InputStreamProgressEvent",
      "org.postgresql.largeobject.LargeObject",
      "uk.ac.sanger.artemis.util.LargeObjectDocument",
      "uk.ac.sanger.artemis.util.LinePushBackReader",
      "uk.ac.sanger.artemis.util.WorkingGZIPInputStream",
      "uk.ac.sanger.artemis.EntryVector",
      "uk.ac.sanger.artemis.SimpleEntryGroup",
      "uk.ac.sanger.artemis.ActionController",
      "uk.ac.sanger.artemis.ActionVector",
      "uk.ac.sanger.artemis.FeatureVector",
      "uk.ac.sanger.artemis.util.FastVector",
      "uk.ac.sanger.artemis.FilteredEntryGroup",
      "uk.ac.sanger.artemis.FilteredEntryGroup$1",
      "uk.ac.sanger.artemis.FilteredEntryGroup$2",
      "uk.ac.sanger.artemis.FilteredEntryGroup$3",
      "uk.ac.sanger.artemis.components.EntryEdit",
      "uk.ac.sanger.artemis.util.TextDocument",
      "uk.ac.sanger.artemis.components.filetree.FileList",
      "org.biojava.bio.seq.io.GenbankFormat",
      "org.biojava.bio.seq.io.GenbankXmlFormat",
      "org.biojava.bio.seq.io.SequenceBuilderBase",
      "org.biojava.bio.seq.io.SimpleAssemblyBuilder$SSBFactory",
      "org.biojava.bio.seq.io.SimpleAssemblyBuilder",
      "org.biojava.utils.ChangeType",
      "org.biojava.utils.Unchangeable",
      "org.biojava.bio.symbol.EmptyAlphabet",
      "org.biojava.bio.symbol.Alphabet",
      "org.biojava.bio.seq.io.WordTokenization",
      "org.biojava.bio.seq.io.NameTokenization",
      "org.biojava.utils.ChangeListener$AlwaysVetoListener",
      "org.biojava.utils.ChangeListener$LoggingListener",
      "org.biojava.utils.ChangeListener",
      "org.biojava.bio.seq.db.EmblCDROMIndexStore",
      "org.biojava.bio.seq.db.emblcd.EmblCDROMIndexReader",
      "org.biojava.bio.seq.db.emblcd.DivisionLkpReader",
      "org.biojava.bio.seq.db.emblcd.RecordParser",
      "uk.ac.sanger.artemis.components.variant.VCFRecord",
      "uk.ac.sanger.artemis.sequence.AminoAcidSequence",
      "uk.ac.sanger.artemis.FeaturePatternPredicate",
      "uk.ac.sanger.artemis.components.filetree.RemoteFileNode",
      "uk.ac.sanger.artemis.util.RemoteFileDocument",
      "uk.ac.sanger.artemis.j2ssh.FileTransferProgressMonitor",
      "org.emboss.jemboss.JembossParams",
      "org.emboss.jemboss.gui.Browser",
      "uk.ac.sanger.artemis.Selection",
      "uk.ac.sanger.artemis.FeatureSegmentVector",
      "uk.ac.sanger.artemis.SimpleGotoEventSource",
      "uk.ac.sanger.artemis.components.BasePlotGroup"
    );
  }
}
